"""
Tiny HTTPS static file server for webxr_controller.html.

WebTransport only exists in a secure context (https), so the controller
page must be served over TLS, not plain http.server. Reuses the same
cert.pem / key.pem generated by setup_cert.py.

Run this on the same machine serving webxr_controller.html (e.g. the Pi):
    python3 https_server.py

Then on the Quest Browser, go to:
    https://<that machine's IP>:8443/webxr_controller.html

The browser will warn "connection is not private" (self-signed cert) —
tap Advanced → Proceed. This is expected and safe on your own LAN.
"""

import http.server
import ssl
from pathlib import Path

HOST = "0.0.0.0"
PORT = 8443
CERT_FILE = Path("cert.pem")
KEY_FILE = Path("key.pem")

if not CERT_FILE.exists() or not KEY_FILE.exists():
    print(f"ERROR: {CERT_FILE} or {KEY_FILE} not found. Run setup_cert.py first.")
    raise SystemExit(1)

httpd = http.server.ThreadingHTTPServer((HOST, PORT), http.server.SimpleHTTPRequestHandler)
ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
ctx.load_cert_chain(certfile=str(CERT_FILE), keyfile=str(KEY_FILE))
httpd.socket = ctx.wrap_socket(httpd.socket, server_side=True)

print(f"Serving HTTPS on {HOST} port {PORT} ...")
print(f"  Open:  https://<this machine's IP>:{PORT}/webxr_controller.html")
httpd.serve_forever()
